# Generated by Django 4.2.6 on 2023-10-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('collection', models.CharField(max_length=200, null=True)),
                ('pricePerDay', models.CharField(max_length=200)),
                ('pricePerMonth', models.CharField(max_length=200)),
                ('imageLink', models.CharField(max_length=1000)),
            ],
        ),
    ]
