# Generated by Django 4.2.6 on 2023-10-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_collection_cars_rentelstatus_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playground.collection'),
        ),
    ]
