# Generated by Django 4.2.6 on 2023-11-22 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_order_ordernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custoumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('licenesId', models.CharField(max_length=100)),
                ('orderAt', models.DateField(auto_now_add=True)),
                ('endDate', models.DateField(null=True)),
                ('orderNote', models.CharField(max_length=500, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.cars')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
