# Generated by Django 4.2.7 on 2023-12-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_custoumer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
